<?php /* @var $user \ZfcUserCrud\Entity\User */?>
<div class="page-header">
    <h3>
        <?php echo $this->translate('Users');?>
    </h3>
</div>
<div class="row">
    <div class="col-md-3">
        <a class="btn btn-info" href="<?php echo $this->url('zfc-user-crud', array('action' => 'new')); ?>">
            <span class="glyphicon glyphicon-plus"></span>
        <?php echo $this->translate('New User');?> 
        </a>
    </div>
    <div class="col-md-9">
        <form class="form-inline" role="form" method="post">
            <div class="form-group">
                <label class="sr-only" for="searchTerm">
                    <?php echo $this->translate('Search');?>: 
                </label>
                <input type="text" class="form-control" id="searchTerm" 
                       value="<?php echo $searchTerm; ?>"
                       placeholder="<?php echo $this->translate('Name');?>" 
                       name="searchTerm"/>
            </div>
            <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-search"></span>
                <?php echo $this->translate('Search');?>
            </button>
        </form>
    </div>
</div>
<br/>

<table class="table table-hover table-responsive table-striped">
    <tr>
        <th>
            <?php echo $this->translate('Name');?>
        </th>
        <th>
            <?php echo $this->translate('Username');?>
        </th>
        <th>
            <?php echo $this->translate('Email');?>
        </th>
        <th>
            <?php echo $this->translate('Edit');?>
        </th>
        <th>
            <?php echo $this->translate('Remove');?>
        </th>
    </tr>
    <?php foreach ($users as $user): ?>
    <tr>
        <td>
            <?php echo $user->getDisplayName();?>
        </td>
        <td>
            <?php echo $user->getUsername();?>
        </td>
        <td>
            <?php echo $user->getEmail();?>
        </td>
        <td>
                <a href="
                <?php
                echo $this->url('zfc-user-crud', array(
                    'action' => 'edit',
                    'id' => $user->getId()
                ));
                ?>"
                   >
                    <span class="glyphicon glyphicon-edit"></span>
                    <?php echo $this->translate('Edit');?>
                </a>
            </td>
            <td>
                <a href="
                <?php
                echo $this->url('zfc-user-crud', array(
                    'action' => 'remove',
                    'id' => $user->getId()
                ));
                ?>"
                   onclick="return confirm('<?php echo $this->translate('Confirm to remove this item');?>')"
                   >
                    <span class="glyphicon glyphicon-trash"></span>
                    <?php echo $this->translate('Remove');?>
                </a>
            </td>
    </tr>
    <?php endforeach; ?>
</table>

<?php
echo $this
        ->paginationControl(
                $users, 'Sliding', 'partial/paginator', array('route' => 'zfc-user-crud'));
?>