<div class="page-header">
    <h3>
        <?php echo $this->translate('User');?>
        <small>- <?php echo $this->translate('Add New');?></small>
    </h3>
</div>
<a class="btn btn-info" href="<?php echo $this->url('zfc-user-crud'); ?>">
    <span class="glyphicon glyphicon-backward"></span>
    <?php echo $this->translate('Cancel');?>
</a>
<br/>
<br/>
<?php echo $this->form()->openTag($form); ?>
<?php foreach ($form as $element): ?>
    <div class="form-group">
        <label for="<?php echo $element->getName(); ?>" class="col-sm-2 control-label">
            <?php echo $element->getLabel(); ?>
        </label>
        <div class="col-sm-10">
            <?php echo $this->formElement($element); ?>
            <?php if ($this->formElementErrors($element)): ?>
                <div class="alert alert-danger alert-dismissable">
                    <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button>
                    <?php echo $this->formElementErrors($element); ?>    
                </div>
            <?php endif; ?>

        </div>
    </div>
<?php endforeach; ?>
<?php echo $this->form()->closeTag($form); ?>